config/routes.rb
Rails.application.routes.draw do

  resources :users
  patch 'update_current/:id', to: 'users#update_current', as: :update_current


  resources :ideas

  resources :competitions do
    resources :ideas

  end

  get 'run/:id', to: 'competitions#run', as: :competition_runs
  get 'buy/:id', to: 'competitions#buy', as: :competition_buys
  get 'sell/:id', to: 'competitions#sell', as: :competition_sells


  root to: 'competitions#index'
  # For details on the DSL available within this file, see  http://guides.rubyonrails.org/routing.html
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :competition
  has_one :market, dependent: :destroy
  has_one :user
  after_create :add_market


  def shares_per_user(user_id)
    self.market.sales.where(:user_id => user_id).sum(:share)
  end

  private

  def add_market
    self.market=Market.create
  end



end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :get_competition, except: [:create]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = @competition.ideas
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
    @idea=Idea.find(idea_params)
    @competition=@idea.competition
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.create(idea_params)
    @competition=@idea.competition


    respond_to do |format|
      if @idea.save
        format.html { redirect_to competition_ideas_path(@competition), notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:title, :description, :competition_id)
    end

    def get_competition
      @competition=Competition.find(params[:competition_id])
    end
end

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Competition: <%= @competition.competition_name %></h2>

  <%= form.hidden_field :competition_id, :value => @competition.id %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table id="index_table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>


    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.description %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_competition_idea_path(@competition) %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>