config/routes.rb
Rails.application.routes.draw do

  resources :users
  patch 'update_current/:id', to: 'users#update_current', as: :update_current


  resources :ideas

  resources :competitions do
    resources :ideas

  end

  get 'run/:id', to: 'competitions#run', as: :competition_runs
  get 'buy/:id', to: 'competitions#buy', as: :competition_buys
  get 'sell/:id', to: 'competitions#sell', as: :competition_sells


  root to: 'competitions#index'
  # For details on the DSL available within this file, see  http://guides.rubyonrails.org/routing.html
end

app/models/competition.rb
class Competition < ApplicationRecord
  has_many :ideas, dependent: :destroy
  has_many :markets, through: :ideas



  def ideas_by_marketprice
    self.ideas.includes('market').order('markets.price desc')
  end




  def maxwins_per_user(user_id)
    maxwin=0
    self.ideas_by_marketprice.each_with_index do |idea,index|
      maxwin += idea.shares_per_user(user_id)
      break if index==self.maxwins-1
    end
    return maxwin
end




end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy, :run]
  before_action :update_user

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end


  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url, notice: 'Competition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  ######## NON REST Actions #########################################

  def run

  end

  def buy
    market=Market.find(params[:id])
    market.buy(1,session[:user_id])
    market.save!
    @competition=market.idea.competition
    render :run
  end

  def sell
    market=Market.find(params[:id])
    market.buy(-1,session[:user_id])
    @competition=market.idea.competition
    render :run
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:competition_name, :max_markets, :market_velocity_b, :id, :maxwins)
    end

    def update_user
      unless @user.nil?
        @user.reload
      end
    end
end

app/views/competitions/_form.html.erb
<%= form_with(model: competition, local: true) do |form| %>
  <% if competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% competition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :competition_name %>
    <%= form.text_field :competition_name %>
  </div>

  <div class="field">
    <%= form.label :max_markets %>
    <%= form.number_field :max_markets %>
  </div>

  <div class="field">
    <%= form.label 'Market Velocity, large B - large liquidity' %>
    <%= form.number_field :market_velocity_b %>
  </div>

  <div class="field">
    <%= form.label :max_winning_markets %>
    <%= form.number_field :maxwins %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing Competition</h1>

<%= render 'form', competition: @competition %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Competitions</h1>

<table id=index_table>
  <thead>
    <tr>
      <th>Competition name</th>
      <th>Max markets</th>
      <th>Market velocity b</th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= competition.competition_name %></td>
        <td><%= competition.max_markets %></td>
        <td><%= competition.market_velocity_b %></td>
        <td><%= link_to 'RUN', competition_runs_path(competition) %></td>
        <td><%= link_to 'Maintain Ideas', competition %></td>
        <td><%= link_to 'Maintain Parameters', edit_competition_path(competition) %></td>
        <td><%= link_to '!!DELETE!!', competition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Competition', new_competition_path %>

app/views/competitions/new.html.erb
<h1>New Competition</h1>

<%= render 'form', competition: @competition %>

<%= link_to 'Back', competitions_path %>

app/views/competitions/run.html.erb
<p id="notice"><%= notice %></p>



<h1>Running Competition" <%= @competition.competition_name %>"</h1>
<% @user.reload %>

<div style="background-color: orange;padding: 5px; width: 400px">
  <h2><%= @user.name %></h2>
  <p>You have <%= @user.credit_print %></p>
  <p>Possible Shares WINNING:<%= @competition.maxwins_per_user(@user.id) %></p>
</div>

</br>
<h2>Vote for the best ideas</h2>

<table id="index_table">


  <thead>
  <tr>
    <th>Position</th>
    <th>Title</th>
    <th>Price</th>
    <th>Good Idea</th>
    <th>I dont like</th>
    <th>My Shares</th>
  </tr>
  </thead>

  <tbody>


  <% @competition.ideas_by_marketprice.each_with_index do |idea, index| %>


    <% if index < @competition.maxwins %>
      <tr bgcolor="#4CAF50" ;>

    <% else %>
      <tr bgcolor="#dcdcdc">
    <% end %>


    <td style='text-align:center'>
      <%= index + 1 %>
      <% case idea.market.tendency %>
      <% when :up %>
        &uarr;
      <% when :down %>
        &darr;
      <% end %>
    </td>


    <td><%= idea.title %></td>
    <td style='text-align:center'><%= idea.market.price_print %></td>

    <td>

      <% if @user.credit > idea.market.price %>
        <%= form_tag(competition_buys_path(idea.market), method: "get") do %>
          <% if idea.shares_per_user(@user.id) > 0 %>
            <%= submit_tag("Love it, buy MORE!") %>
          <% else %>
            <%= submit_tag("I love this idea, buy it!") %>
          <% end %>
        <% end %>
      <% else %>
      NO CREDIT
      <%end %>
    </td>

    <td>
      <% if idea.shares_per_user(@user.id) > 0 %>
        <%= form_tag(competition_sells_path(idea.market), method: "get") do %>
          <%= submit_tag("Not sure, get out!") %>
        <% end %>
      <% end %>
    </td>
    <td style='text-align:center'><%= idea.shares_per_user(@user.id) %></td>

    </tr>
  <% end %>
  </tbody>
</table>
</div>


<br>

<p>From all ideas, the top 3 (green) ideas will be evealuated/implemented.</p>
<p>One idea (the best idea of the 3) will be announced. Your Shares of this idea will win</p>


<%= link_to "Refresh", competition_runs_path(@competition) %>

app/views/competitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Competition name:</strong>
  <%= @competition.competition_name %>
</p>

<p>
  <strong>Max markets:</strong>
  <%= @competition.max_markets %>
</p>

<p>
  <strong>Market velocity b:</strong>
  <%= @competition.market_velocity_b %>
</p>

<p>
  <strong>Max Wins:</strong>
  <%= @competition.maxwins %>
</p>


<%= link_to 'New idea', new_competition_idea_path(@competition) %> |

<%= link_to 'List ideas', competition_ideas_path(@competition) %> |

<%= link_to 'Edit', edit_competition_path(@competition) %> |
<%= link_to 'Back', competitions_path %>