config/routes.rb
Rails.application.routes.draw do

  resources :users
  patch 'update_current/:id', to: 'users#update_current', as: :update_current


  resources :ideas

  resources :competitions do
    resources :ideas

  end

  get 'run/:id', to: 'competitions#run', as: :competition_runs
  get 'buy/:id', to: 'competitions#buy', as: :competition_buys
  get 'sell/:id', to: 'competitions#sell', as: :competition_sells


  root to: 'competitions#index'
  # For details on the DSL available within this file, see  http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Innomine1</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%unless @user.new_record? %>
<div style="background-color: grey;margin-bottom: 5px;display: inline-block;float: right" align="right" >
<%= form_for @user, url: update_current_path(@user) do |f| %>
  <%= f.select :id, User.all.collect { |p| [ p.name, p.id ] }, include_blank: true %>
  <%= f.submit %>
<% end %>
<% end %>

</div>
<header>

  <div class="nav">
    <ul>
    <%if @user.nil? || @user.id==1%>
        <p style="color: red; font-size: x-large  ">!!!UPDATE USER BEFORE RUNNING A COMPETITION!!</p>
        <%else %>
        <p>        <%=@user.name %></p>
        <%end %>
      <li><%= link_to "Maintain Competition", competitions_path %></li>
      <li><%= link_to "Maintain User", users_path %></li>

    </ul>
  </div>

</header>

<%= yield %>
</body>
</html>